'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Mail, Pause, Send, XCircle } from 'lucide-react';
import { PageContainer } from '@/components/layout/page-container';
import { PageHeader } from '@/components/shared/page-header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { tiendaNubeApiClient } from '@/lib/tiendanube-api-client';
import { useToastStore } from '@/stores/toast-store';
import type { Campaign, CampaignLog } from '@/types/tiendanube';

export default function CampaignDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const addToast = useToastStore((state) => state.addToast); const [id, setId] = useState(''); const [campaign, setCampaign] = useState<Campaign | null>(null); const [logs, setLogs] = useState<CampaignLog[]>([]); const [testEmail, setTestEmail] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  const load = async (campaignId: string) => { setLoading(true); try { const [loadedCampaign, loadedLogs] = await Promise.all([tiendaNubeApiClient.getCampaign(campaignId), tiendaNubeApiClient.getCampaignLogs(campaignId)]); setCampaign(loadedCampaign); setLogs(loadedLogs); } catch (error) { addToast(error instanceof Error ? error.message : 'No se pudo cargar la campaña.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void params.then(({ id: campaignId }) => { setId(campaignId); return load(campaignId); }); }, [params]);
  const action = async (kind: 'test' | 'schedule' | 'pause' | 'cancel') => { if (!id) return; if (kind === 'test' && !testEmail) { addToast('Ingresá un email de prueba.', 'error'); return; } setWorking(true); try { if (kind === 'test') await tiendaNubeApiClient.sendCampaignTest(id, testEmail); if (kind === 'schedule') await tiendaNubeApiClient.scheduleCampaign(id); if (kind === 'pause') await tiendaNubeApiClient.pauseCampaign(id); if (kind === 'cancel') await tiendaNubeApiClient.cancelCampaign(id); addToast(kind === 'test' ? 'Prueba enviada.' : 'Acción aplicada.', 'success'); await load(id); } catch (error) { addToast(error instanceof Error ? error.message : 'No se pudo completar la acción.', 'error'); } finally { setWorking(false); } };
  if (loading || !campaign) return <PageContainer><p className="p-6 text-muted-foreground">Cargando campaña...</p></PageContainer>;
  const percentage = campaign.totalRecipients ? Math.round(((campaign.sentCount + campaign.failedCount) / campaign.totalRecipients) * 100) : 0;
  return <PageContainer><PageHeader title={campaign.name} description={campaign.subject}><div className="flex gap-2"><Link href="/gestion-tienda-nube/campaigns"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4" />Volver</Button></Link><Badge variant={campaign.status === 'completed' ? 'default' : 'secondary'}>{campaign.status}</Badge></div></PageHeader><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><Card><CardHeader><CardTitle>Progreso del envío</CardTitle><CardDescription>{campaign.sentCount} enviados, {campaign.failedCount} errores, de {campaign.totalRecipients} destinatarios.</CardDescription></CardHeader><CardContent><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${percentage}%` }} /></div><p className="mt-2 text-sm text-muted-foreground">{percentage}% procesado</p></CardContent></Card><Card><CardHeader><CardTitle>Últimos resultados</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Destinatario</TableHead><TableHead>Estado</TableHead><TableHead>Detalle</TableHead></TableRow></TableHeader><TableBody>{logs.map((log) => <TableRow key={log.id}><TableCell>{log.recipient}</TableCell><TableCell><Badge variant={log.status === 'error' ? 'destructive' : 'secondary'}>{log.status}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{log.errorMessage || log.sentAt || '-'}</TableCell></TableRow>)}{logs.length === 0 ? <TableRow><TableCell colSpan={3} className="h-20 text-center text-muted-foreground">Todavía no hay envíos registrados.</TableCell></TableRow> : null}</TableBody></Table></CardContent></Card></div><div className="space-y-6"><Card><CardHeader><CardTitle>Enviar prueba</CardTitle><CardDescription>Verificá contenido y remitente antes de activar.</CardDescription></CardHeader><CardContent className="space-y-3"><Input type="email" value={testEmail} onChange={(event) => setTestEmail(event.target.value)} placeholder="tu@email.com" /><Button className="w-full" variant="outline" onClick={() => void action('test')} disabled={working}><Mail className="mr-2 h-4 w-4" />Enviar prueba</Button></CardContent></Card><Card><CardHeader><CardTitle>Acciones</CardTitle></CardHeader><CardContent className="space-y-2">{campaign.status === 'draft' ? <Button className="w-full" onClick={() => void action('schedule')} disabled={working}><Send className="mr-2 h-4 w-4" />Enviar ahora</Button> : null}{campaign.status === 'sending' || campaign.status === 'scheduled' ? <Button className="w-full" variant="outline" onClick={() => void action('pause')} disabled={working}><Pause className="mr-2 h-4 w-4" />Pausar</Button> : null}{campaign.status !== 'completed' && campaign.status !== 'cancelled' ? <Button className="w-full" variant="destructive" onClick={() => void action('cancel')} disabled={working}><XCircle className="mr-2 h-4 w-4" />Cancelar</Button> : null}</CardContent></Card></div></div></PageContainer>;
}
